-- phpMyAdmin SQL Dump
-- version 3.5.8.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Apr 11, 2014 at 09:51 PM
-- Server version: 5.5.36-MariaDB
-- PHP Version: 5.5.9

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `nova`
--

-- --------------------------------------------------------

--
-- Table structure for table `pages`
--

CREATE TABLE IF NOT EXISTS `pages` (
  `uid` int(10) NOT NULL AUTO_INCREMENT,
  `page_id` varchar(255) NOT NULL,
  `page_title` varchar(255) NOT NULL,
  `nav_custom` varchar(255) NOT NULL,
  `timestamp` int(10) NOT NULL,
  `active` tinyint(1) NOT NULL,
  `version` int(10) NOT NULL,
  `sequence` varchar(255) NOT NULL,
  `xml` longtext NOT NULL,
  `js_includes` varchar(255) NOT NULL,
  `plugins` longtext NOT NULL,
  `plugin_styles` longtext NOT NULL,
  `page_styles` longtext NOT NULL,
  `scripts` longtext NOT NULL,
  `init_scripts` longtext NOT NULL,
  PRIMARY KEY (`page_id`),
  UNIQUE KEY `uid` (`uid`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=20 ;

--
-- Dumping data for table `pages`
--

INSERT INTO `pages` (`uid`, `page_id`, `page_title`, `nav_custom`, `timestamp`, `active`, `version`, `sequence`, `xml`, `js_includes`, `plugins`, `plugin_styles`, `page_styles`, `scripts`, `init_scripts`) VALUES
(1, '01-00-00-001', 'Dashboard', '', 1394226489, 1, 1, '', '<page>\r\n	<subtitle>Home</subtitle>\r\n</page>', 'portlet-pricehistory', '<script src="plugins/jquery.peity.min.js" type="text/javascript"></script>\r\n<script src="plugins/gritter/js/jquery.gritter.js" type="text/javascript"></script>\r\n<!-- IMPORTANT! fullcalendar depends on jquery-ui-1.10.3.custom.min.js for drag & drop support -->\r\n<script src="plugins/fullcalendar/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>\r\n<script src="plugins/jquery.sparkline.min.js" type="text/javascript"></script>\r\n<script src="js/page-dashboard-sortable.js"></script>', '<link href="plugins/gritter/css/jquery.gritter.css" rel="stylesheet" type="text/css"/>\r\n<link href="plugins/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" type="text/css"/>\r\n<link href="plugins/bootstrap-tour-master/assets/css/bootstrap-tour.css" rel="stylesheet">', '<link href="css/pages/tasks.css" rel="stylesheet" type="text/css"/>\r\n<script src="js/Chart.js"></script>', '<script src="js/app.js" type="text/javascript"></script>\r\n<script src="js/index.js" type="text/javascript"></script>  \r\n<script src="js/tasks.js" type="text/javascript"></script>\r\n\r\n<script src="js/system-highstock.js"></script> ', ' <script>\n      jQuery(document).ready(function() {    \n         App.init(); // initlayout and core plugins\n         Index.init();\n         Index.initCalendar(); // init index page''s custom scripts\n         PortletDraggable.init();\n      });\n   </script>'),
(5, '02-00-00-001', 'Trade Wizard', '', 1395781175, 1, 1, '001', '<page>\n	<subtitle>Make A Trade</subtitle>\n</page>', '', '<script type="text/javascript" src="plugins/jquery-validation/dist/jquery.validate.min.js"></script>\r\n<script type="text/javascript" src="plugins/jquery-validation/dist/additional-methods.min.js"></script>\r\n<script type="text/javascript" src="plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js"></script>\r\n<script type="text/javascript" src="plugins/select2/select2.min.js"></script>\r\n<script type="text/javascript" src="plugins/data-tables/jquery.dataTables.min.js"></script>\r\n<script type="text/javascript" src="plugins/data-tables/DT_bootstrap.js"></script>', '<link rel="stylesheet" type="text/css" href="plugins/select2/select2_mds.css" />\r\n<link rel="stylesheet" href="plugins/data-tables/DT_bootstrap.css" />\r\n<link href="plugins/bootstrap-tour-master/assets/css/bootstrap-tour.css" rel="stylesheet">', '', '<script src="js/app.js"></script>\r\n<script src="js/form-wizard.js"></script>\r\n<script src="js/table-advanced.js"></script>', '<script>\r\n      jQuery(document).ready(function() {       \r\n         // initiate layout and plugins\r\n         App.init();\r\n         FormWizard.init();\r\n         TableAdvanced.init();\r\n      });\r\n</script>'),
(6, '02-00-00-002', 'Open Orders', '', 1395786576, 1, 1, '002', '<page>\n	<subtitle>All Open Tickets</subtitle>\n</page>', '', '<script type="text/javascript" src="plugins/select2/select2.min.js"></script>\n<script type="text/javascript" src="plugins/data-tables/jquery.dataTables.min.js"></script>\n<script type="text/javascript" src="plugins/data-tables/DT_bootstrap.js"></script>', '<link rel="stylesheet" type="text/css" href="plugins/select2/select2_mds.css" />\n<link rel="stylesheet" href="plugins/data-tables/DT_bootstrap.css" />\n<link href="plugins/bootstrap-tour-master/assets/css/bootstrap-tour.css" rel="stylesheet">', '', '<script src="js/app.js"></script>\r\n<script src="js/table-advanced.js"></script>', '<script>\r\n      jQuery(document).ready(function() {       \r\n         App.init();\r\n         TableAdvanced.init();\r\n      });\r\n</script>'),
(7, '02-00-00-003', 'Recent Orders', '', 1395789034, 1, 1, '002', '<page>\n	<subtitle>Recently Closed Tickets</subtitle>\n</page>', '', '<script type="text/javascript" src="plugins/select2/select2.min.js"></script>\r\n<script type="text/javascript" src="plugins/data-tables/jquery.dataTables.min.js"></script>\r\n<script type="text/javascript" src="plugins/data-tables/DT_bootstrap.js"></script>', '<link rel="stylesheet" type="text/css" href="plugins/select2/select2_mds.css" />\r\n<link rel="stylesheet" href="plugins/data-tables/DT_bootstrap.css" />\r\n<link href="plugins/bootstrap-tour-master/assets/css/bootstrap-tour.css" rel="stylesheet">', '', '<script src="js/app.js"></script>\r\n<script src="js/table-advanced.js"></script>', '<script>\r\n      jQuery(document).ready(function() {       \r\n         App.init();\r\n         TableAdvanced.init();\r\n      });\r\n</script>'),
(8, '03-01-00-001', 'Overview', '', 1395874515, 1, 1, '', '<page>\n	<subtitle>Overview</subtitle>\n</page>', 'portlet-pricehistory|portlet-save-fund-overview', '<script src="plugins/jquery.peity.min.js" type="text/javascript"></script>\r\n<script src="plugins/gritter/js/jquery.gritter.js" type="text/javascript"></script>\r\n<script src="plugins/jquery.sparkline.min.js" type="text/javascript"></script> \r\n<!--<script src="js/page-dashboard-sortable.js"></script>-->', '<script src="js/Chart.js"></script>\r\n<link href="plugins/gritter/css/jquery.gritter.css" rel="stylesheet" type="text/css"/>\r\n', '<link href="css/pages/tasks.css" rel="stylesheet" type="text/css"/>', '<script src="js/app.js" type="text/javascript"></script>\r\n<script src="js/index.js" type="text/javascript"></script>  \r\n<script src="js/tasks.js" type="text/javascript"></script> \r\n   \r\n<script src="js/system-highstock.js"></script> ', '<script>\r\n      jQuery(document).ready(function() {    \r\n         App.init(); // initlayout and core plugins\r\n         Index.init();\r\n         PortletDraggable.init();\r\n      });\r\n</script>'),
(13, '03-01-00-002', 'Admin', '', 1395940440, 1, 1, '', '<page>\n	<uri>?page=03-01-01-003</uri>\n	<subtitle>Administration &amp; Fund Settings</subtitle>\n</page>', '', '<script type="text/javascript" src="plugins/select2/select2.min.js"></script>\r\n', '<link rel="stylesheet" type="text/css" href="plugins/select2/select2_mds.css" />', '', '<script src="js/app.js"></script>\r\n<script src="js/form-samples.js"></script> ', '<script>\r\n      jQuery(document).ready(function() {    \r\n         // initiate layout and plugins\r\n         App.init();\r\n         FormSamples.init();\r\n      });\r\n</script>\r\n'),
(14, '03-01-00-004', 'Ledger', '', 1395940440, 1, 1, '', '<page>\n	<subtitle>Ledger</subtitle>\n</page>', '', '<script type="text/javascript" src="plugins/select2/select2.min.js"></script>\r\n<script type="text/javascript" src="plugins/data-tables/jquery.dataTables.min.js"></script>\r\n<script type="text/javascript" src="plugins/data-tables/DT_bootstrap.js"></script>', '<link rel="stylesheet" type="text/css" href="plugins/select2/select2_mds.css" />\r\n<link rel="stylesheet" href="plugins/data-tables/DT_bootstrap.css" />', '', '<script src="js/app.js"></script>\r\n<script src="js/table-advanced.js"></script>', '<script>\r\n      jQuery(document).ready(function() {       \r\n         App.init();\r\n         TableAdvanced.init();\r\n      });\r\n</script>'),
(15, '03-01-00-005', 'Public Profile', '', 1395940440, 1, 1, '', '<page><subtitle>Public Profile</subtitle></page>', '', '<script src="plugins/jqvmap/jqvmap/jquery.vmap.js" type="text/javascript"></script>   \n   <script src="plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js" type="text/javascript"></script>\n   <script src="plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>\n   <script src="plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js" type="text/javascript"></script>\n   <script src="plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js" type="text/javascript"></script>\n   <script src="plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js" type="text/javascript"></script>\n   <script src="plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js" type="text/javascript"></script>  \n   <script src="plugins/jquery.peity.min.js" type="text/javascript"></script>\n   <script src="plugins/jquery.pulsate.min.js" type="text/javascript"></script>\n   <script src="plugins/jquery-knob/js/jquery.knob.js" type="text/javascript"></script>\n   <script src="plugins/flot/jquery.flot.js" type="text/javascript"></script>\n   <script src="plugins/flot/jquery.flot.resize.js" type="text/javascript"></script>\n   <script src="plugins/bootstrap-daterangepicker/moment.min.js" type="text/javascript"></script>\n   <script src="plugins/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>     \n   <script src="plugins/gritter/js/jquery.gritter.js" type="text/javascript"></script>\n<script src="plugins/fullcalendar/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>\n<script src="plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.js" type="text/javascript"></script>\n<script src="plugins/jquery.sparkline.min.js" type="text/javascript"></script>  ', '<script src="js/Chart.js"></script>\r\n<link href="plugins/gritter/css/jquery.gritter.css" rel="stylesheet" type="text/css"/>\r\n<link href="plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css"/>', '<link href="css/pages/profile.css" rel="stylesheet" type="text/css" />', '<script src="js/app.js"></script>\r\n<script src="js/index.js" type="text/javascript"></script>  \r\n<script src="js/tasks.js" type="text/javascript"></script>', '<script>\r\n      jQuery(document).ready(function() {       \r\n         // initiate layout and plugins\r\n         App.init();\r\n		 Index.init();\r\n         Index.initCalendar(); // init index page''s custom scripts\r\n         Index.initCharts(); // init index page''s custom scripts\r\n         Index.initChat();\r\n         Index.initMiniCharts();\r\n         Index.initPeityElements();\r\n         Index.initKnowElements();\r\n         Index.initDashboardDaterange();\r\n      });\r\n</script>'),
(12, '03-01-01-002', 'Performance Stocks', 'Stocks', 1395940440, 1, 1, '', '<page>\n	<subtitle>Performance Attribution Analysis by Stocks</subtitle>\n</page>', '', '', '', '', '<script src="js/app.js"></script>', '<script>\r\n      jQuery(document).ready(function() {       \r\n         // initiate layout and plugins\r\n         App.init();\r\n      });\r\n</script>'),
(11, '03-01-01-003', 'Performance Zones', 'Zones', 1395940440, 1, 1, '', '<page>\n	<uri>?page=03-01-01-003</uri>\n	<subtitle>Performance Attribution Analysis by Zones</subtitle>\n</page>', '', '', '', '', '<script src="js/app.js"></script>', '<script>\r\n      jQuery(document).ready(function() {       \r\n         // initiate layout and plugins\r\n         App.init();\r\n      });\r\n</script>'),
(9, '03-01-02-001', 'Alpha Contour', '', 1395876252, 1, 1, '', '<page>\n	<id>03-01-02-001/id>\n	<uri>?page=03-01-02-001</uri>\n	<currentPage>Alpha Contour</currentPage>\n	<title>Fund Symbol</title>\n	<subtitle>Alpha Contour</subtitle>\n</page>', '', '<script type="text/javascript" src="plugins/select2/select2.min.js"></script>', '<link rel="stylesheet" type="text/css" href="plugins/select2/select2_mds.css" />', '', '<script src="js/app.js"></script>\r\n<script src="js/form-samples.js"></script', '<script>\r\n      jQuery(document).ready(function() {    \r\n         // initiate layout and plugins\r\n         App.init();\r\n         FormSamples.init();\r\n      });\r\n</script>'),
(10, '03-01-02-002', 'Alpha Scatter', '', 1395884280, 1, 1, '', '<page>\n	<id>03-01-02-002/id>\n	<uri>?page=03-01-02-002</uri>\n	<currentPage>Alpha Scatter</currentPage>\n	<title>Fund Symbol</title>\n	<subtitle>Alpha Scatter</subtitle>\n</page>', '', '<script type="text/javascript" src="plugins/select2/select2.min.js"></script>', '<link rel="stylesheet" type="text/css" href="plugins/select2/select2_mds.css" />', '', '<script src="js/app.js"></script>\r\n<script src="js/form-samples.js"></script>', '<script>\r\n      jQuery(document).ready(function() {    \r\n         // initiate layout and plugins\r\n         App.init();\r\n         FormSamples.init();\r\n      });\r\n</script>'),
(16, '03-01-03-002', 'Strat. Sector', 'Sector', 1395940440, 1, 1, '', '<page>\n	<subtitle>Stratification By Sector</subtitle>\n</page>', '', '', '<script src="js/Chart.js"></script>', '', '<script src="js/app.js"></script>', '<script>\r\n      jQuery(document).ready(function() {       \r\n         // initiate layout and plugins\r\n         App.init();\r\n      });\r\n</script>'),
(17, '03-01-03-003', 'Strat. Style', 'Style', 1395940440, 1, 1, '', '<page>\n	<subtitle>Stratification By Style</subtitle>\n</page>', '', '', '<script src="js/Chart.js"></script>', '', '<script src="js/app.js"></script>', '<script>\r\n      jQuery(document).ready(function() {       \r\n         // initiate layout and plugins\r\n         App.init();\r\n      });\r\n</script>'),
(19, '05-01-00-002', 'Test', 'Testing', 1396291838, 1, 1, '', '', '', '', '', '', '', ''),
(4, '10-00-00-001', 'Setup Wizard', '', 1395333840, 1, 1, '', '<page>\n	<id>4</id>\n	<uri>?page=4</uri>\n	<currentPage>Account Setup</currentPage>\n	<title>Setup Wizard</title>\n	<subtitle>Account Setup</subtitle>\n</page>', '', '   <script type="text/javascript" src="plugins/jquery-validation/dist/jquery.validate.min.js"></script>\r\n   <script type="text/javascript" src="plugins/jquery-validation/dist/additional-methods.min.js"></script>\r\n   <script type="text/javascript" src="plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js"></script>\r\n   <script type="text/javascript" src="plugins/select2/select2.min.js"></script>', '<link rel="stylesheet" type="text/css" href="plugins/select2/select2_mds.css" />', '', '   <script src="js/app.js"></script>\n   <script src="js/setup-wizard.js"></script>', '   <script>\n      jQuery(document).ready(function() {       \n         // initiate layout and plugins\n         App.init();\n         SetupWizard.init();\n      });\n   </script>'),
(2, '11-00-00-001', 'Login', '', 1394560416, 1, 1, '', '', '', '        <script src="plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>\n	<script type="text/javascript" src="plugins/select2/select2.min.js"></script> ', '<link rel="stylesheet" type="text/css" href="plugins/select2/select2_mds.css" />', '<link href="css/pages/login.css" rel="stylesheet" type="text/css"/>', '        <script src="js/app.js" type="text/javascript"></script>\n	<script src="js/login.js" type="text/javascript"></script>', '        <script>\n		jQuery(document).ready(function() {     \n		  App.init();\n		  Login.init();\n		});\n	</script>'),
(3, '11-00-00-002', 'Change Password', '', 1394560416, 1, 1, '', '', '', '        <script src="plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>\n	<script type="text/javascript" src="plugins/select2/select2.min.js"></script> ', '<link rel="stylesheet" type="text/css" href="plugins/select2/select2_mds.css" />', '<link href="css/pages/login.css" rel="stylesheet" type="text/css"/>', '        <script src="js/app.js" type="text/javascript"></script>\n	<script src="js/password-reset.js" type="text/javascript"></script>\n        \n', '        <script>\n		jQuery(document).ready(function() {     \n		  App.init();\n		  PWReset.init();\n		});\n	</script>');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
